target 'XiaoYing' do
    
    pod 'AFNetworking','~>2.6.3'
    pod 'Masonry'
    pod 'SDWebImage'
    pod 'ZBarSDK'
    pod 'FMDB'
    pod 'libqrencode'
    pod 'Toast'
    pod 'JSONKit-NoWarning', '~> 1.2'
    pod 'CocoaAsyncSocket', '~> 7.4.3'
    pod 'RongCloudIM/IMLib', '2.8.3'
    pod 'RongCloudIM/IMKit', '2.8.3'
    
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    
    # U-Share(友盟) SDK UI模块（分享面板，建议添加）
    pod ‘UMengUShare/UI’
    
    # 集成微信
    pod ‘UMengUShare/Social/WeChat'
    
    # 集成QQ
    pod ‘UMengUShare/Social/QQ'
    
    # 集成新浪微博
    pod ‘UMengUShare/Social/Sina'
    
    # 集成邮件
    pod ‘UMengUShare/Social/Email'
    
end

